[package]
name = "cs165_project1"
version = "0.1.0"
authors = ["Calvin <tacalvin123@gmail.com>"]
edition = "2018"

[dependencies]
md5 = "0.6.1"
rust-crypto = "0.2.36"
hex = "0.3.2"
crypto-hash = "0.3.3"
